### PR TITLE
Update 10.0 Masque skinning

### PR DESCRIPTION
**Pull request by StormFX**
The first commit  re-enables Bag Bar skinning for Masque and ensures that the proper type is passed to Masque. Feel free to tweak it or even not use it. Just throwing it out there as a quick fix.

The second commit fixes issues with PetButton skinning in Dragonflight. Primarily the issue with textures being stretched when a skin uses an atlas.

Some notes:

- Masque handles hiding the Gloss and Shadow on empty buttons automatically.
- The Backdrop shouldn't be hidden on empty buttons if the grid is enabled and the backdrop is enabled for the skin, so I removed that bit as it's unnecessary since the Backdrop visibility is also handled by Masque.

### CODE REVIEW

**Comment by Nevcairiel** [comment]
I've been testing this, but I don't really like how it handles the bag bar.
image

By default it drastically changes the appearance of the bar from the sleek modern design to the classic square design, mismatching the UI style. Also, the Backpack icon is just missing.

I would like the default to be no visual change, unless the user explicitly asks for one.

**Comment by StormFX** [comment]
That looks like the Default (Classic) skin. The Default skin should look exactly like the Dragonflight bag bar.

**Comment by StormFX** [comment]
That looks like the Default (Classic) skin. The Default skin should look exactly like the Dragonflight bag bar.

**Comment by Nevcairiel** [comment]
I made sure nothing was configued for the Bag Bar in Masque (removed the entire group from the SV), and then loaded it in, resulting in this design. Classic was selected in the UI, not Default.

**Comment by StormFX** [comment]
Oh yeah. I forgot that while Default (Classic) and Default are the fallback skins, Classic is set to be the default if no skin has been selected. If you select Default, it should look right. I've been meaning to update the default skin for Dragonflight, but I've got Classic hard-coded in a few places, so I need to sift through the code and fix it. The primary reason FWIW, Classic is set as the default is so that users don't load Masque and then try to figure out why nothing's changed (which would happen if the skin was Blizzard-style) for their client.

**Comment by Nevcairiel** [comment]
I've done some larger cleanup in the Pet Button that should supersede your changes.

Is there something I can do to not have everyones bag bar turn into ugly classic style when I enable the skinning again?
I thought about adding an option to enable/disable skinning per bar, but I would rather it be enabled by default, but actually use the native skin, and not the old on.

**Comment by StormFX** [comment]
> Is there something I can do to not have everyones bag bar turn into ugly classic style when I enable the skinning again?

As I mentioned above, it depends on what skin they already have selected for Bartender4. To get the new Dragonflight bag style, all they have to do is select "Default" for Bartender's Bag Bar or just Disable the Bag Bar in Masque's options. It's worth noting, the style that you're seeing is from the "Classic" skin, which is currently set as the default skin on a fresh profile. Most users will see whatever skin settings they've already chosen.

**Comment by StormFX** [comment]
To demonstrate:

After resetting the profile in Masque:

image

Then selecting the new "Default" skin for Bartender's Bag Bar:

image

**Comment by Nevcairiel** [comment]
And my point is that I rather not have users see the classic skin. I have spent a lot of time trying to make Bartender4 on 10.0 look good, not old.

**Comment by Nevcairiel** [comment]
Adapted and merged the bar change manually as f6f00f6b731b8533006d109cb4191fb01ee78eb0

**Comment by StormFX** [comment]
> And my point is that I rather not have users see the classic skin. I have spent a lot of time trying to make Bartender4 on 10.0 look good, not old.

I understand and respect that. The next build of Masque will have the native skins for clients be the default, rather than the Classic skin. That should address that issue. I appreciate what you've done. Thank you!

**Pull request closed without merging**
